#lang sicp

(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Недостаточно денег на счете"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch call-password m)
    (cond ((not (eq? call-password password))
           (lambda (x) "Неверный пароль -- MAKE-ACCOUNT"))
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Неизвестный вызов -- MAKE-ACCOUNT"
                       m))))
  dispatch)

(define (make-joint acc acc-password new-password)
  (define (dispatch call-password m)
    (if (not (eq? call-password new-password))
        (lambda (x) "Неверный пароль добавленного счёта -- MAKE-JOINT")
        (acc acc-password m)))
  (if (eq? ((acc acc-password 'withdraw) 0) "Неверный пароль -- MAKE-ACCOUNT")
      (lambda (x y)
        (lambda (z) "Неверный пароль исходного счёта -- MAKE-JOINT"))
      dispatch))

(define peter-acc (make-account 100 '123))
(define paul-acc (make-joint peter-acc '123 'jopa))

((paul-acc 'jopa 'withdraw) 10)
((paul-acc 'jopa 'withdraw) 10)
((paul-acc 'jopa 'withdraw) 10)
((peter-acc '123 'withdraw) 10)
((paul-acc 'jopa 'withdraw) 10)
((peter-acc '123 'withdraw) 10)
